version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "05:24"
  target-branch: ci/dependency-updates
  labels:
    - CI/CD
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "05:18"
  # Should be bigger than or equal to the total number of dependencies (currently 2+2)
  open-pull-requests-limit: 10
  target-branch: ci/dependency-updates
  labels:
    - CI/CD
