name: CI - Update dependencies PR

on:
  schedule:
    # At 6:30 UTC on the first of every month
    - cron: "30 6 1 * *"
  workflow_dispatch:

env:
  DEPENDABOT_BRANCH: ci/dependency-updates
  GIT_USER_NAME: "Casper Welzel Andersen"
  GIT_USER_EMAIL: "casper+github@welzel.nu"

jobs:
  create-collected-pr:
    name: Single dependabot PR
    if: github.repository_owner == 'CasperWA'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository (default branch)
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install `pre-commit` and dependencies
      run: |
        python -m pip install -U pip
        pip install -U setuptools wheel
        pip install -r requirements.txt -r requirements_dev.txt

    - name: Set up git user info
      run: |
        git config --global user.name "${{ env.GIT_USER_NAME }}"
        git config --global user.email "${{ env.GIT_USER_EMAIL }}"

    - name: Reset to '${{ env.DEPENDABOT_BRANCH }}'
      run: |
        git fetch origin ${{ env.DEPENDABOT_BRANCH }}:${{ env.DEPENDABOT_BRANCH }}
        git reset --hard ${{ env.DEPENDABOT_BRANCH }}

    - name: Auto-update `pre-commit` hooks
      run: |
        pre-commit autoupdate

        if [ -n "$(git status --porcelain .pre-commit-config.yaml)" ]; then
          # Set environment variable notifying next steps that the hooks changed
          echo "Pre-commit hooks have been updated !"
          echo "UPDATED_PRE_COMMIT_HOOKS=true" >> $GITHUB_ENV
        else
          echo "No pre-commit hooks have been updated."
          echo "UPDATED_PRE_COMMIT_HOOKS=false" >> $GITHUB_ENV
        fi

    - name: Possibly run `pre-commit` with updated hooks
      if: env.UPDATED_PRE_COMMIT_HOOKS == 'true'
      continue-on-error: true  # Still create the PR if this step fails
      run: SKIP=pylint pre-commit run --all-files

    - name: Possibly commit changes and updates
      if: env.UPDATED_PRE_COMMIT_HOOKS == 'true'
      run: git commit -am "Update \`pre-commit\` hooks"

    - name: Fetch PR body
      id: pr_body
      uses: chuhlomin/render-template@v1.5
      with:
        template: .github/utils/single_dependency_pr_body.txt

    - name: Create PR
      id: cpr
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.RELEASE_PAT }}
        committer: "${{ env.GIT_USER_NAME }} <${{ env.GIT_USER_EMAIL }}>"
        author: "${{ env.GIT_USER_NAME }} <${{ env.GIT_USER_EMAIL }}>"
        branch: ci/update-dependencies
        delete-branch: true
        title: "[Auto-generated] Update dependencies"
        body: ${{ steps.pr_body.outputs.result }}
        labels: CI/CD

    - name: Information
      run: 'echo "${{ steps.cpr.outputs.pull-request-operation }} PR #${{ steps.cpr.outputs.pull-request-number }}: ${{ steps.cpr.outputs.pull-request-url }}"'
