name: CD - Release

on:
  release:
    types:
      - "publish"

jobs:
  publish:
    name: Call reusable workflow
    if: github.repository == 'CasperWA/gh-actions' && startsWith(github.ref, 'refs/tags/v')
    uses: ./.github/workflows/cd_release.yml
    with:
      git_username: "Casper Welzel Andersen"
      git_email: "casper+github@welzel.nu"
      python_package: false
      release_branch: main
      python_version: "3.9"
      build_cmd: ".github/utils/update_tags.sh"
      update_docs: true
      doc_extras: "[docs]"
      changelog_exclude_tags_regex: "^v[0-9]+$"
    secrets:
      PAT: ${{ secrets.RELEASE_PAT }}
